CREATE DATABASE NEWDEPOSIT;
USE NEWDEPOSIT;

CREATE TABLE PRODUSE (
   Id_Produs INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
   Cod_Produs INT(3) NOT NULL,
   Nume_Produs VARCHAR(30),
   Cantitate INT(5) NOT NULL DEFAULT 1,
   Pret DOUBLE NOT NULL);
   
INSERT PRODUSE VALUES
   (1, 123, 'primulProdus', 3, 12.25),
   (2, 234, 'alDoileaProdus', 6, 9.99),
   (3, 345, 'alTreileaProdus', 9, 58.92),
   (4, 456, 'calPatruleaProdus', 99, 1500.00),
   (5, 567, 'alCinceleaProdus', 151, 99.45),
   (6, 678, 'alSaseleaProdus', 245, 985),
   (7, 789, 'CalSapteleaProdus', 999, 60000.00),
   (8, 890, 'alOpteleaProdus', 4599, 1.99),
   (9, 901, 'alNoualeaProdus', 58, 67.01),
   (10, 369, 'alZeceleaProdus', 13, 3.69);    
   
SELECT * FROM PRODUSE;

DROP TABLE FURNIZORI; -- STERGI TABELUL
CREATE TABLE FURNIZORI (
	ID_FURNIZOR INT AUTO_INCREMENT PRIMARY KEY,
    NUME_FURNIZOR VARCHAR(50),
    NUME_PRODUS VARCHAR(50),
    NUMAR_CONTRACT INT);
ALTER TABLE FURNIZORI CHANGE ID_FURNIZOR id_FURNIZOR INT AUTO_INCREMENT; 

TRUNCATE FURNIZORI; # STERGI DATELE DIN TABEL
INSERT INTO FURNIZORI (NUME_FURNIZOR, NUME_PRODUS, NUMAR_CONTRACT) VALUES
	('FURNIZOR_1', 'alCinceleaProdus', 1), 
	('FURNIZOR_1', 'alOpteleaProdus', 1), 
	('FURNIZOR_2', 'alZeceleaProdus', 2), 
	('FURNIZOR_3', 'alNoualeaProdus', 3), 
	('FURNIZOR_3', 'CalSapteleaProdus', 3), 
	('FURNIZOR_4', 'calPatruleaProdus', 5),
	('FURNIZOR_2', 'calPatruleaProdus', 7);

SELECT * FROM PRODUSE INNER JOIN FURNIZORI ON PRODUSE.NUME_PRODUS = FURNIZORI.NUME_PRODUS;
SELECT FURNIZORI.NUME_FURNIZOR, PRODUSE.CANTITATE, PRODUSE.NUME_PRODUS AS 'Nume Produse'
	FROM PRODUSE INNER JOIN FURNIZORI ON PRODUSE.NUME_PRODUS = FURNIZORI.NUME_PRODUS;

# rezultate identice in ambele cazuri
SELECT * FROM FURNIZORI LEFT JOIN PRODUSE USING (NUME_PRODUS);
SELECT * FROM PRODUSE RIGHT JOIN FURNIZORI USING (NUME_PRODUS);

SELECT * FROM PRODUSE LEFT JOIN FURNIZORI USING (NUME_PRODUS);
SELECT * FROM FURNIZORI RIGHT JOIN PRODUSE USING (NUME_PRODUS);

SELECT * FROM PRODUSE CROSS JOIN FURNIZORI;
SELECT * FROM PRODUSE, FURNIZORI WHERE PRODUSE.NUME_PRODUS = FURNIZORI.NUME_PRODUS;

-- select dn produse si ordonam dupa codul produsului
SELECT * FROM PRODUSE ORDER BY COD_PRODUS;
-- select din furnizori si ordonam descrescator dupa nume
SELECT * FROM fURNIZORI ORDER BY NUME_FURNIZOR DESC;

SELECT ID_PRODUS FROM PRODUSE UNION ALL SELECT ID_FURNIZOR FROM FURNIZORI;

SELECT * FROM FURNIZORI;

